services:
  elasticsearch-node1:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: es-node1
    environment:
      - node.name=es-node1
      - cluster.name=forum-cluster
      - discovery.seed_hosts=es-node2,es-node3
      - cluster.initial_master_nodes=es-node1,es-node2,es-node3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.license.self_generated.type=basic
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data1:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - forum-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  elasticsearch-node2:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: es-node2
    environment:
      - node.name=es-node2
      - cluster.name=forum-cluster
      - discovery.seed_hosts=es-node1,es-node3
      - cluster.initial_master_nodes=es-node1,es-node2,es-node3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.license.self_generated.type=basic
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data2:/usr/share/elasticsearch/data
    networks:
      - forum-network
    depends_on:
      - elasticsearch-node1

  elasticsearch-node3:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: es-node3
    environment:
      - node.name=es-node3
      - cluster.name=forum-cluster
      - discovery.seed_hosts=es-node1,es-node2
      - cluster.initial_master_nodes=es-node1,es-node2,es-node3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.license.self_generated.type=basic
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data3:/usr/share/elasticsearch/data
    networks:
      - forum-network
    depends_on:
      - elasticsearch-node1

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: forum-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://es-node1:9200
      - xpack.security.enabled=false
    ports:
      - "5601:5601"
    networks:
      - forum-network
    depends_on:
      elasticsearch-node1:
        condition: service_healthy

volumes:
  es-data1:
  es-data2:
  es-data3:

networks:
  forum-network:
    driver: bridge
